# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:12:01+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Product(BaseModel):
    attributes: Optional[List[str]] = None
    name: Optional[str] = None
    price: Optional[str] = None
    url: Optional[str] = None


class ProductResponse(BaseModel):
    products: Optional[List[Product]] = None
